reads_dir: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/reads"
temp_dir: "/data/tmp/elewilso"
params_file: "hash_to_parameters.tsv"
# output directory: where your results will be generated
# to use the current directory, leave it empty
output: #"/private/groups/patenlab/elewilso/giraffe-parameter-search" 
mapper: 


experiments:

  map_hifi_1k:
    gbz_graph: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.gbz"
    distance_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.dist"
    minimizer_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.withzip.min"
    zipfile: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.zipcodes" 
    sample: HG002
    realness: real
    tech: hifi 
    subset: 1k
    preset: hifi

  map_hifi_10k:
    gbz_graph: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.gbz"
    distance_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.dist"
    minimizer_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.withzip.min"
    zipfile: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.zipcodes" 
    sample: HG002
    realness: real
    tech: hifi 
    subset: 10k
    preset: hifi

  map_hifi_100k:
    gbz_graph: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.gbz"
    distance_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.dist"
    minimizer_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.withzip.min"
    zipfile: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.zipcodes" 
    sample: HG002
    realness: real
    tech: hifi 
    subset: 100k
    preset: hifi

  map_hifi_1m:
    gbz_graph: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.gbz"
    distance_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.dist"
    minimizer_index: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.withzip.min"
    zipfile: "/private/groups/patenlab/anovak/projects/hprc/lr-giraffe/graphs/hprc-v2.1-mc-chm13-eval-sampled16o_fragmentlinked-for-real-hifi-HG002-full.k31.w50.W.zipcodes" 
    sample: HG002
    realness: real
    tech: hifi 
    subset: 1m
    preset: hifi

  map_custom:
    reference: 
    gbz_graph: 
    distance_index: 
    minimizer_index: 
    zipfile: 
    sample: 
    realness: 
    tech:  
    subset: 
    preset: 


# write the names of stats you want to record in the output tsv (mapping_stats.tsv).
# list of supported statistics are under supported_stats in the Snakefile.
# to automatically record all available, you can write "all"
included_statistics:
  - all

# write the names of stats you want to exclude from the output tsv.
# helpful if you want most stats ('all' in included_statistics) except a few. 
excluded_statistics:
  - speed


# to create graphs, write the name or names of stats you want to plot parameter values against.
# list of supported statistics are under supported_stats in the Snakefile.

desired_2d_graphs:
  - clipped_or_unmapped
  - reads_incorrect
  
desired_3d_graphs:
  - [speed_from_log, clipped_or_unmapped]